Repository UMC-7th-DANTHIS/backend, pull requests merged in 2025-02, with the labels that each got.

#39 [Refactor] 댄서 등록, 수정, 조회 및 찜 등록, 해제 api 패키지 구조 개선
  src/main/java/com/danthis/backend/api/user/UserController.java
  src/main/java/com/danthis/backend/application/dancer/DancerService.java
  src/main/java/com/danthis/backend/application/dancer/implement/DancerManager.java
  src/main/java/com/danthis/backend/application/dancer/implement/mapping/DancerGenreManager.java
  src/main/java/com/danthis/backend/application/dancer/implement/mapping/DancerGenreReader.java
  src/main/java/com/danthis/backend/application/dancer/implement/mapping/DancerImageManager.java
  src/main/java/com/danthis/backend/application/dancer/implement/mapping/DancerImageReader.java
  src/main/java/com/danthis/backend/application/user/UserService.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/UserDancerManager.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/UserDancerReader.java
  src/main/java/com/danthis/backend/domain/dancer/Dancer.java
  src/main/java/com/danthis/backend/domain/dancer/dancerimage/repository/DancerImageRepository.java
  src/main/java/com/danthis/backend/domain/dancer/dancerimage/repository/DancerImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/dancer/dancerimage/repository/DancerImageRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/mapping/dancergenre/repository/DancerGenreRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/dancergenre/repository/DancerGenreRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/repository/UserDancerRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/repository/UserDancerRepositoryImpl.java
Labels: 🔨 Refactor

#41 [Feature] 마이페이지 - 찜한 댄서, 수업 조회 기능 구현
  src/main/java/com/danthis/backend/api/user/UserController.java
  src/main/java/com/danthis/backend/application/search/response/CommunityPostSearchServiceResponse.java
  src/main/java/com/danthis/backend/application/user/UserService.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/UserDancerManager.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/UserDancerReader.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/WishListManager.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/WishListReader.java
  src/main/java/com/danthis/backend/application/user/response/UserFavoriteResponse.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/repository/UserDancerRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/repository/UserDancerRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/mapping/wishlist/repository/WishListRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/wishlist/repository/WishListRepositoryImpl.java
Labels: ✨ Feature

#44 [Feature] 댄스 수업 예약 기능 구현
  src/main/java/com/danthis/backend/api/chat/ChatController.java
  src/main/java/com/danthis/backend/api/chat/request/ChatBookingRequest.java
  src/main/java/com/danthis/backend/api/danceclass/DanceClassController.java
  src/main/java/com/danthis/backend/api/danceclass/request/DanceClassBookingApproveRequest.java
  src/main/java/com/danthis/backend/api/danceclass/request/DanceClassCreateRequest.java
  src/main/java/com/danthis/backend/application/chat/ChatService.java
  src/main/java/com/danthis/backend/application/chat/implement/ChatManager.java
  src/main/java/com/danthis/backend/application/chat/implement/ChatMapper.java
  src/main/java/com/danthis/backend/application/chat/implement/ChatReader.java
  src/main/java/com/danthis/backend/application/chat/response/ChatBookingServiceResponse.java
  src/main/java/com/danthis/backend/application/chat/response/DancerChatListServiceResponse.java
  src/main/java/com/danthis/backend/application/chat/response/UserChatListServiceResponse.java
  src/main/java/com/danthis/backend/application/danceclass/DanceClassService.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassManager.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassReader.java
  src/main/java/com/danthis/backend/application/danceclass/request/DanceClassCreateServiceRequest.java
  src/main/java/com/danthis/backend/application/danceclass/response/DanceClassBookingServiceResponse.java
  src/main/java/com/danthis/backend/application/dancer/implement/DancerReader.java
  src/main/java/com/danthis/backend/common/exception/ErrorCode.java
  src/main/java/com/danthis/backend/domain/dancer/repository/DancerRepository.java
  src/main/java/com/danthis/backend/domain/mapping/danceclassbooking/DanceClassBooking.java
  src/main/java/com/danthis/backend/domain/mapping/danceclassbooking/repository/DanceClassBookingRepository.java
  src/main/java/com/danthis/backend/domain/mapping/danceclassbooking/repository/DanceClassBookingRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/danceclassbooking/repository/DanceClassBookingRepositoryImpl.java
Labels: ✨ Feature

#43 [Feature] 유저가 쓴 게시글, 리뷰 목록 조회 기능 구현
  src/main/java/com/danthis/backend/api/user/UserController.java
  src/main/java/com/danthis/backend/application/post/implement/PostManager.java
  src/main/java/com/danthis/backend/application/post/implement/PostReader.java
  src/main/java/com/danthis/backend/application/review/implement/ReviewManager.java
  src/main/java/com/danthis/backend/application/review/implement/ReviewReader.java
  src/main/java/com/danthis/backend/application/user/UserService.java
  src/main/java/com/danthis/backend/application/user/response/UserPostsResponse.java
  src/main/java/com/danthis/backend/application/user/response/UserReviewResponse.java
  src/main/java/com/danthis/backend/domain/classreview/repository/ClassReviewRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/classreview/repository/ClassReviewRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/communitycomment/repository/CommunityCommentRepository.java
  src/main/java/com/danthis/backend/domain/communitycomment/repository/CommunityCommentRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/communitycomment/repository/CommunityCommentRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/communitypost/repository/CommunityPostRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/communitypost/repository/CommunityPostRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/dancer/Dancer.java
Labels: ✨ Feature

#46 [Feature] 댄스수업 찜 등록, 해제 API 구현
  src/main/java/com/danthis/backend/api/danceclass/DanceClassController.java
  src/main/java/com/danthis/backend/application/danceclass/DanceClassService.java
  src/main/java/com/danthis/backend/application/user/UserService.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/UserDancerManager.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/WishListManager.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/WishListReader.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/UserDancer.java
  src/main/java/com/danthis/backend/domain/mapping/wishlist/WishList.java
  src/main/java/com/danthis/backend/domain/mapping/wishlist/repository/WishListRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/wishlist/repository/WishListRepositoryImpl.java
Labels: ✨ Feature

#51 [bugfix] 중복으로 찜이 되는 버그 수정
  src/main/java/com/danthis/backend/application/danceclass/DanceClassService.java
  src/main/java/com/danthis/backend/application/user/UserService.java
  src/main/java/com/danthis/backend/common/exception/ErrorCode.java
Labels: 🐞 BugFix

#54 [Feature] 댄서가 등록한 수업 목록 조회 기능 구현
  src/main/java/com/danthis/backend/api/danceclass/DanceClassController.java
  src/main/java/com/danthis/backend/application/danceclass/DanceClassService.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassReader.java
  src/main/java/com/danthis/backend/domain/danceclass/repository/DanceClassRepository.java
Labels: ✨ Feature

#49 [Feature] 유저가 수강한 수업 목록 조회 기능
  src/main/java/com/danthis/backend/api/danceclass/DanceClassController.java
  src/main/java/com/danthis/backend/application/danceclass/DanceClassService.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassReader.java
Labels: ✨ Feature

#55 [Feature] 커뮤니티 관련 API 구현
  src/main/java/com/danthis/backend/api/community/CommunityController.java
  src/main/java/com/danthis/backend/api/community/request/CommentCreateRequest.java
  src/main/java/com/danthis/backend/api/community/request/PostCreateRequest.java
  src/main/java/com/danthis/backend/api/community/request/PostUpdateRequest.java
  src/main/java/com/danthis/backend/api/file/FileController.java
  src/main/java/com/danthis/backend/application/community/CommentService.java
  src/main/java/com/danthis/backend/application/community/PostService.java
  src/main/java/com/danthis/backend/application/community/implement/CommentManager.java
  src/main/java/com/danthis/backend/application/community/implement/CommentMapper.java
  src/main/java/com/danthis/backend/application/community/implement/CommentReader.java
  src/main/java/com/danthis/backend/application/community/implement/PostManager.java
  src/main/java/com/danthis/backend/application/community/implement/PostMapper.java
  src/main/java/com/danthis/backend/application/community/implement/PostReader.java
  src/main/java/com/danthis/backend/application/community/implement/mapping/PostImageManager.java
  src/main/java/com/danthis/backend/application/community/request/CommentCreateServiceRequest.java
  src/main/java/com/danthis/backend/application/community/request/PostCreateServiceRequest.java
  src/main/java/com/danthis/backend/application/community/request/PostUpdateServiceRequest.java
  src/main/java/com/danthis/backend/application/community/response/CommentListServiceResponse.java
  src/main/java/com/danthis/backend/application/community/response/PostListServiceResponse.java
  src/main/java/com/danthis/backend/application/community/response/PostReadServiceResponse.java
  src/main/java/com/danthis/backend/application/post/implement/PostReader.java
  src/main/java/com/danthis/backend/application/user/UserService.java
  src/main/java/com/danthis/backend/common/exception/ErrorCode.java
  src/main/java/com/danthis/backend/domain/communitycomment/repository/CommunityCommentRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/communitycomment/repository/CommunityCommentRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/communitypost/CommunityPost.java
  src/main/java/com/danthis/backend/domain/communitypost/communitypostimage/repository/CommunityPostImageRepository.java
  src/main/java/com/danthis/backend/domain/communitypost/communitypostimage/repository/CommunityPostImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/communitypost/communitypostimage/repository/CommunityPostImageRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/communitypost/repository/CommunityPostRepository.java
  src/main/java/com/danthis/backend/domain/communitypost/repository/CommunityPostRepositoryCustom.java
Labels: ✨ Feature

#63 [Feature] 해시태그 검색 및 커뮤니티 삭제 기능 구현
  src/main/java/com/danthis/backend/api/search/SearchController.java
  src/main/java/com/danthis/backend/application/community/CommentService.java
  src/main/java/com/danthis/backend/application/community/PostService.java
  src/main/java/com/danthis/backend/application/community/implement/CommentReader.java
  src/main/java/com/danthis/backend/application/file/response/GetPresignedUrlResponse.java
  src/main/java/com/danthis/backend/application/search/SearchService.java
  src/main/java/com/danthis/backend/application/search/implement/SearchReader.java
  src/main/java/com/danthis/backend/application/search/response/ClassSearchServiceResponse.java
  src/main/java/com/danthis/backend/domain/communitycomment/repository/CommunityCommentRepository.java
  src/main/java/com/danthis/backend/domain/danceclass/repository/DanceClassRepository.java
  src/main/java/com/danthis/backend/domain/danceclass/repository/DanceClassRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/danceclass/repository/DanceClassRepositoryImpl.java
Labels: ✨ Feature, 🔨 Refactor

#67 [Feature] 게시글, 댄서 조회 리스폰스 수정 & 자신의 댄서 조회 API 구현
  src/main/java/com/danthis/backend/api/dancer/DancerController.java
  src/main/java/com/danthis/backend/application/community/implement/PostManager.java
  src/main/java/com/danthis/backend/application/dancer/DancerService.java
  src/main/java/com/danthis/backend/application/dancer/response/DancerInfoResponse.java
  src/main/java/com/danthis/backend/application/user/response/UserPostsResponse.java
Labels: ✨ Feature

#57 [Feature] 댄스 수업 수정 및 삭제 기능 구현
  src/main/java/com/danthis/backend/api/danceclass/DanceClassController.java
  src/main/java/com/danthis/backend/api/danceclass/request/DanceClassUpdateRequest.java
  src/main/java/com/danthis/backend/application/danceclass/DanceClassService.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassManager.java
  src/main/java/com/danthis/backend/application/danceclass/implement/mapping/DanceClassHashtagManager.java
  src/main/java/com/danthis/backend/application/danceclass/implement/mapping/DanceClassImageManager.java
  src/main/java/com/danthis/backend/application/danceclass/request/DanceClassUpdateServiceRequest.java
  src/main/java/com/danthis/backend/application/review/implement/ReviewManager.java
  src/main/java/com/danthis/backend/application/review/implement/mapping/ReviewImageManager.java
  src/main/java/com/danthis/backend/domain/classreview/classreviewimage/repository/ClassReviewImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/classreview/classreviewimage/repository/ClassReviewImageRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/classreview/repository/ClassReviewRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/classreview/repository/ClassReviewRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/danceclass/DanceClass.java
  src/main/java/com/danthis/backend/domain/danceclass/danceclassimage/repository/DanceClassImageRepository.java
  src/main/java/com/danthis/backend/domain/danceclass/danceclassimage/repository/DanceClassImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/danceclass/danceclassimage/repository/DanceClassImageRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/mapping/danceclassbooking/repository/DanceClassBookingRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/danceclassbooking/repository/DanceClassBookingRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/mapping/danceclasshashtag/repository/DanceClassHashtagRepository.java
  src/main/java/com/danthis/backend/domain/mapping/danceclasshashtag/repository/DanceClassHashtagRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/danceclasshashtag/repository/DanceClassHashtagRepositoryImpl.java
Labels: ✨ Feature

#73 [Refactor] 리뷰 기능 수정
  src/main/java/com/danthis/backend/api/review/ReviewController.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassMapper.java
  src/main/java/com/danthis/backend/application/danceclass/response/DanceClassReadServiceResponse.java
  src/main/java/com/danthis/backend/application/review/ReviewService.java
  src/main/java/com/danthis/backend/application/review/implement/ReviewManager.java
  src/main/java/com/danthis/backend/domain/classreview/classreviewimage/repository/ClassReviewImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/classreview/classreviewimage/repository/ClassReviewImageRepositoryImpl.java
Labels: ✨ Feature, 🔨 Refactor

#72 [Refactor] 댄서가 등록한 수업 조회 api & 댄서 정보 변경 api 수정
  src/main/java/com/danthis/backend/api/dancer/DancerController.java
  src/main/java/com/danthis/backend/api/dancer/request/DancerUpdateRequest.java
  src/main/java/com/danthis/backend/application/danceclass/DanceClassService.java
  src/main/java/com/danthis/backend/application/dancer/DancerService.java
Labels: 🔨 Refactor

#75 [Refactor] 수업에 등록하는 유저 목록 수정
  src/main/java/com/danthis/backend/api/file/FileController.java
  src/main/java/com/danthis/backend/application/danceclass/DanceClassService.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassMapper.java
  src/main/java/com/danthis/backend/application/danceclass/response/EligibleUserListServiceResponse.java
Labels: 🔨 Refactor

#78 [Refactor] 댄스 수업 이미지 자료형 변환
  src/main/java/com/danthis/backend/application/danceclass/DanceClassService.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassManager.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassMapper.java
Labels: 🔨 Refactor

#82 [Refactor] 오픈 채팅 링크 반환
  src/main/java/com/danthis/backend/api/chat/ChatController.java
  src/main/java/com/danthis/backend/api/chat/response/ChatStartResponse.java
  src/main/java/com/danthis/backend/api/danceclass/request/DanceClassCreateRequest.java
  src/main/java/com/danthis/backend/api/danceclass/request/DanceClassUpdateRequest.java
  src/main/java/com/danthis/backend/application/chat/ChatService.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassMapper.java
  src/main/java/com/danthis/backend/application/danceclass/implement/mapping/DanceClassImageManager.java
  src/main/java/com/danthis/backend/application/danceclass/request/DanceClassCreateServiceRequest.java
  src/main/java/com/danthis/backend/application/danceclass/request/DanceClassUpdateServiceRequest.java
Labels: 🔨 Refactor

#83 [Refactor] 댄서 리스폰스 중 장르 이름 변경
  src/main/java/com/danthis/backend/application/dancer/DancerService.java
  src/main/java/com/danthis/backend/application/dancer/response/DancerInfoResponse.java
Labels: 🔨 Refactor

#85 [Fix] 수업 이미지 순서 에러 해결
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassMapper.java
Labels: 🐞 BugFix

#86 [Deploy] 배포용 리디렉션 uri로 변경
  Dockerfile
Labels: 🌏 Deploy

#90 [Feature] 모든 댄서 및 수업 조회 API에서 장르 및 해시태그 조회 기능 추가
  src/main/java/com/danthis/backend/api/danceclass/DanceClassController.java
  src/main/java/com/danthis/backend/api/dancer/DancerController.java
  src/main/java/com/danthis/backend/application/danceclass/response/DanceClassListServiceResponse.java
  src/main/java/com/danthis/backend/application/dancer/DancerService.java
  src/main/java/com/danthis/backend/application/dancer/implement/DancerManager.java
  src/main/java/com/danthis/backend/application/dancer/response/DancerSummaryListResponse.java
  src/main/java/com/danthis/backend/domain/danceclass/DanceClass.java
  src/main/java/com/danthis/backend/domain/dancer/Dancer.java
Labels: ✨ Feature

#89 [Fix] 수정 관련 문제 및 썸네일 해결
  src/main/java/com/danthis/backend/api/review/ReviewController.java
  src/main/java/com/danthis/backend/api/review/request/ReviewUpdateRequest.java
  src/main/java/com/danthis/backend/application/danceclass/response/DanceClassListServiceResponse.java
  src/main/java/com/danthis/backend/application/review/ReviewService.java
  src/main/java/com/danthis/backend/application/review/implement/ReviewManager.java
  src/main/java/com/danthis/backend/application/review/implement/mapping/ReviewImageManager.java
  src/main/java/com/danthis/backend/application/review/request/ReviewUpdateServiceRequest.java
  src/main/java/com/danthis/backend/domain/classreview/ClassReview.java
Labels: ✨ Feature, 🐞 BugFix

#94 [Fix] 리뷰 이미지 문제 해결
  src/main/java/com/danthis/backend/api/review/request/ReviewCreateRequest.java
  src/main/java/com/danthis/backend/api/review/request/ReviewUpdateRequest.java
  src/main/java/com/danthis/backend/application/review/implement/ReviewManager.java
  src/main/java/com/danthis/backend/application/review/implement/ReviewMapper.java
  src/main/java/com/danthis/backend/application/review/response/ReviewReadServiceResponse.java
  src/main/java/com/danthis/backend/common/config/SecurityConfig.java
  src/main/java/com/danthis/backend/common/security/jwt/JwtFilter.java
Labels: 🐞 BugFix
