Repository UMC-7th-DANTHIS/backend, pull requests merged in 2025-01, with the labels that each got.

#9 [Feature] 카카오 소셜 로그인 구현
  .gitignore
  src/main/java/com/danthis/backend/api/ApiResponse.java
  src/main/java/com/danthis/backend/api/GlobalExceptionHandler.java
  src/main/java/com/danthis/backend/api/auth/AuthController.java
  src/main/java/com/danthis/backend/api/auth/util/TokenCookieManager.java
  src/main/java/com/danthis/backend/api/auth/util/TokenExtractor.java
  src/main/java/com/danthis/backend/application/auth/AuthService.java
  src/main/java/com/danthis/backend/application/auth/implement/KakaoLoginManager.java
  src/main/java/com/danthis/backend/application/auth/implement/TokenManager.java
  src/main/java/com/danthis/backend/application/auth/implement/TokenProvider.java
  src/main/java/com/danthis/backend/application/auth/implement/TokenReader.java
  src/main/java/com/danthis/backend/application/auth/oauth/KakaoUserDetailsService.java
  src/main/java/com/danthis/backend/application/auth/request/TokenServiceRequest.java
  src/main/java/com/danthis/backend/application/auth/response/TokenServiceResponse.java
  src/main/java/com/danthis/backend/application/user/UserService.java
  src/main/java/com/danthis/backend/application/user/implement/UserManager.java
  src/main/java/com/danthis/backend/application/user/implement/UserReader.java
  src/main/java/com/danthis/backend/common/config/QueryDSLConfig.java
  src/main/java/com/danthis/backend/common/config/RedisConfig.java
  src/main/java/com/danthis/backend/common/config/SecurityConfig.java
  src/main/java/com/danthis/backend/common/config/SwaggerConfig.java
  src/main/java/com/danthis/backend/common/config/WebConfig.java
  src/main/java/com/danthis/backend/common/exception/BusinessException.java
  src/main/java/com/danthis/backend/common/exception/ErrorCode.java
  src/main/java/com/danthis/backend/common/exception/ErrorResponse.java
  src/main/java/com/danthis/backend/common/security/aop/AssignCurrentUserInfo.java
  src/main/java/com/danthis/backend/common/security/aop/AssignCurrentUserInfoAspect.java
  src/main/java/com/danthis/backend/common/security/aop/AssignOrNullCurrentUserInfo.java
  src/main/java/com/danthis/backend/common/security/aop/CurrentUserInfo.java
  src/main/java/com/danthis/backend/common/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/danthis/backend/common/security/jwt/JwtAuthenticationFailEntryPoint.java
  src/main/java/com/danthis/backend/common/security/jwt/JwtFilter.java
  src/main/java/com/danthis/backend/common/security/oauth/KakaoUserDetails.java
  src/main/java/com/danthis/backend/common/security/oauth/KakaoUserInfo.java
  src/main/java/com/danthis/backend/domain/BaseEntity.java
  src/main/java/com/danthis/backend/domain/user/User.java
  src/main/java/com/danthis/backend/domain/user/repository/UserRepository.java
  src/main/java/com/danthis/backend/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/user/token/BlacklistToken.java
  src/main/java/com/danthis/backend/domain/user/token/RefreshToken.java
  src/main/java/com/danthis/backend/domain/user/token/repository/BlacklistTokenRedisRepository.java
  src/main/java/com/danthis/backend/domain/user/token/repository/RefreshTokenRedisRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ Feature

#8 [Feature] 댄스 수업 엔티티 생성
  src/main/java/com/danthis/backend/domain/classreview/ClassReview.java
  src/main/java/com/danthis/backend/domain/classreview/repository/ClassReviewRepository.java
  src/main/java/com/danthis/backend/domain/classreview/repository/ClassReviewRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/classreview/repository/ClassReviewRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/classreviewimage/ClassReviewImage.java
  src/main/java/com/danthis/backend/domain/classreviewimage/repository/ClassReviewImageRepository.java
  src/main/java/com/danthis/backend/domain/classreviewimage/repository/ClassReviewImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/classreviewimage/repository/ClassReviewImageRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/danceclass/DanceClass.java
  src/main/java/com/danthis/backend/domain/danceclass/repository/DanceClassRepository.java
  src/main/java/com/danthis/backend/domain/danceclass/repository/DanceClassRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/danceclass/repository/DanceClassRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/danceclassimage/DanceClassImage.java
  src/main/java/com/danthis/backend/domain/danceclassimage/repository/DanceClassImageRepository.java
  src/main/java/com/danthis/backend/domain/danceclassimage/repository/DanceClassImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/danceclassimage/repository/DanceClassImageRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/hashtag/Hashtag.java
  src/main/java/com/danthis/backend/domain/mapping/danceclassbooking/DanceClassBooking.java
  src/main/java/com/danthis/backend/domain/mapping/danceclassbooking/repository/DanceClassBookingRepository.java
  src/main/java/com/danthis/backend/domain/mapping/danceclassbooking/repository/DanceClassBookingRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/danceclassbooking/repository/DanceClassBookingRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/mapping/danceclasshashtag/DanceClassHashtag.java
  src/main/java/com/danthis/backend/domain/mapping/danceclasshashtag/repository/DanceClassHashtagRepository.java
  src/main/java/com/danthis/backend/domain/mapping/danceclasshashtag/repository/DanceClassHashtagRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/danceclasshashtag/repository/DanceClassHashtagRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/mapping/wishlist/WishList.java
  src/main/java/com/danthis/backend/domain/mapping/wishlist/repository/WishListRepository.java
  src/main/java/com/danthis/backend/domain/mapping/wishlist/repository/WishListRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/wishlist/repository/WishListRepositoryImpl.java
Labels: ✨ Feature

#6 [Feature] 댄스 장르, 댄서 엔티티 생성
  src/main/java/com/danthis/backend/domain/dancer/Dancer.java
  src/main/java/com/danthis/backend/domain/dancer/repository/DancerRepository.java
  src/main/java/com/danthis/backend/domain/dancerimage/DancerImage.java
  src/main/java/com/danthis/backend/domain/dancerimage/repository/DancerImageRepository.java
  src/main/java/com/danthis/backend/domain/genre/Genre.java
  src/main/java/com/danthis/backend/domain/genre/repository/GenreRepository.java
  src/main/java/com/danthis/backend/domain/mapping/dancergenre/DancerGenre.java
  src/main/java/com/danthis/backend/domain/mapping/dancergenre/repository/DancerGenreRepository.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/UserDancer.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/repository/UserDancerRepository.java
  src/main/java/com/danthis/backend/domain/mapping/usergenre/UserGenre.java
  src/main/java/com/danthis/backend/domain/mapping/usergenre/repository/UserGenreRepository.java
  src/main/java/com/danthis/backend/domain/user/repository/UserRepositoryImpl.java
Labels: ✨ Feature

#12 [Feature] 커뮤니티 관련 엔티티 생성
  src/main/java/com/danthis/backend/domain/communitycomment/CommunityComment.java
  src/main/java/com/danthis/backend/domain/communitycomment/repository/CommunityCommentRepository.java
  src/main/java/com/danthis/backend/domain/communitypost/CommunityPost.java
  src/main/java/com/danthis/backend/domain/communitypost/repository/CommunityPostRepository.java
  src/main/java/com/danthis/backend/domain/communitypostimage/CommunityPostImage.java
  src/main/java/com/danthis/backend/domain/communitypostimage/repository/CommunityPostImageRepository.java
  src/main/java/com/danthis/backend/domain/danceclass/DanceClass.java
  src/main/java/com/danthis/backend/domain/dancer/Dancer.java
  src/main/java/com/danthis/backend/domain/dancer/repository/DancerRepository.java
  src/main/java/com/danthis/backend/domain/dancerimage/DancerImage.java
  src/main/java/com/danthis/backend/domain/dancerimage/repository/DancerImageRepository.java
  src/main/java/com/danthis/backend/domain/genre/Genre.java
  src/main/java/com/danthis/backend/domain/genre/repository/GenreRepository.java
  src/main/java/com/danthis/backend/domain/mapping/dancergenre/DancerGenre.java
  src/main/java/com/danthis/backend/domain/mapping/dancergenre/repository/DancerGenreRepository.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/UserDancer.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/repository/UserDancerRepository.java
  src/main/java/com/danthis/backend/domain/mapping/usergenre/UserGenre.java
  src/main/java/com/danthis/backend/domain/mapping/usergenre/repository/UserGenreRepository.java
Labels: ✨ Feature

#14 [Rename] 이미지파일 구조 변경
  src/main/java/com/danthis/backend/domain/classreview/ClassReview.java
  src/main/java/com/danthis/backend/domain/classreview/classreviewimage/ClassReviewImage.java
  src/main/java/com/danthis/backend/domain/classreview/classreviewimage/repository/ClassReviewImageRepository.java
  src/main/java/com/danthis/backend/domain/classreview/classreviewimage/repository/ClassReviewImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/classreview/classreviewimage/repository/ClassReviewImageRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/classreviewimage/repository/ClassReviewImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/communitypost/communitypostimage/CommunityPostImage.java
  src/main/java/com/danthis/backend/domain/communitypost/communitypostimage/repository/CommunityPostImageRepository.java
  src/main/java/com/danthis/backend/domain/danceclass/DanceClass.java
  src/main/java/com/danthis/backend/domain/danceclass/danceclassimage/DanceClassImage.java
  src/main/java/com/danthis/backend/domain/danceclass/danceclassimage/repository/DanceClassImageRepository.java
  src/main/java/com/danthis/backend/domain/danceclass/danceclassimage/repository/DanceClassImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/danceclass/danceclassimage/repository/DanceClassImageRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/danceclassimage/repository/DanceClassImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/dancer/Dancer.java
  src/main/java/com/danthis/backend/domain/dancer/dancerimage/DancerImage.java
  src/main/java/com/danthis/backend/domain/dancer/dancerimage/repository/DancerImageRepository.java
Labels: 📃 Docs

#16 [Feature] 양방향 매핑 관계 설정
  src/main/java/com/danthis/backend/domain/classreview/ClassReview.java
  src/main/java/com/danthis/backend/domain/classreview/classreviewimage/ClassReviewImage.java
  src/main/java/com/danthis/backend/domain/classreview/classreviewimage/repository/ClassReviewImageRepository.java
  src/main/java/com/danthis/backend/domain/classreview/classreviewimage/repository/ClassReviewImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/classreview/classreviewimage/repository/ClassReviewImageRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/classreviewimage/repository/ClassReviewImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/communitycomment/CommunityComment.java
  src/main/java/com/danthis/backend/domain/communitypost/CommunityPost.java
  src/main/java/com/danthis/backend/domain/communitypost/communitypostimage/CommunityPostImage.java
  src/main/java/com/danthis/backend/domain/communitypost/communitypostimage/repository/CommunityPostImageRepository.java
  src/main/java/com/danthis/backend/domain/danceclass/DanceClass.java
  src/main/java/com/danthis/backend/domain/danceclass/danceclassimage/DanceClassImage.java
  src/main/java/com/danthis/backend/domain/danceclass/danceclassimage/repository/DanceClassImageRepository.java
  src/main/java/com/danthis/backend/domain/danceclass/danceclassimage/repository/DanceClassImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/danceclass/danceclassimage/repository/DanceClassImageRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/danceclassimage/repository/DanceClassImageRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/dancer/Dancer.java
  src/main/java/com/danthis/backend/domain/dancer/dancerimage/DancerImage.java
  src/main/java/com/danthis/backend/domain/dancer/dancerimage/repository/DancerImageRepository.java
  src/main/java/com/danthis/backend/domain/genre/Genre.java
  src/main/java/com/danthis/backend/domain/user/User.java
Labels: ✨ Feature

#17 [Feature] 유저 정보 수정 및 조회 기능 구현
  src/main/java/com/danthis/backend/api/auth/AuthController.java
  src/main/java/com/danthis/backend/api/user/UserController.java
  src/main/java/com/danthis/backend/api/user/request/UserUpdateRequest.java
  src/main/java/com/danthis/backend/application/user/UserService.java
  src/main/java/com/danthis/backend/application/user/implement/UserManager.java
  src/main/java/com/danthis/backend/application/user/implement/UserPreferenceMapper.java
  src/main/java/com/danthis/backend/application/user/implement/UserReader.java
  src/main/java/com/danthis/backend/application/user/request/UserUpdateServiceRequest.java
  src/main/java/com/danthis/backend/application/user/response/UserInfoResponse.java
  src/main/java/com/danthis/backend/domain/mapping/dancergenre/DancerGenre.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/UserDancer.java
  src/main/java/com/danthis/backend/domain/mapping/usergenre/UserGenre.java
  src/main/java/com/danthis/backend/domain/user/User.java
  src/main/java/com/danthis/backend/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/user/repository/UserRepositoryImpl.java
Labels: ✨ Feature

#21 [Feature] 댄스 수업 등록 기능 구현
  src/main/java/com/danthis/backend/api/danceclass/DanceClassController.java
  src/main/java/com/danthis/backend/api/danceclass/request/DanceClassCreateRequest.java
  src/main/java/com/danthis/backend/application/danceclass/DanceClassService.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassManager.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassMapper.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassReader.java
  src/main/java/com/danthis/backend/application/danceclass/request/DanceClassCreateServiceRequest.java
  src/main/java/com/danthis/backend/common/exception/ErrorCode.java
  src/main/java/com/danthis/backend/domain/hashtag/repository/HashtagRepository.java
Labels: ✨ Feature

#26 [Feature] PresignedUrl 설정
  build.gradle
  src/main/java/com/danthis/backend/api/file/FileController.java
  src/main/java/com/danthis/backend/application/file/FileService.java
  src/main/java/com/danthis/backend/application/file/response/GetPresignedUrlResponse.java
  src/main/java/com/danthis/backend/common/config/S3Config.java
Labels: ✨ Feature

#29 [Deploy] 무중단 배포 자동화 구축
  .github/workflows/danthis_dev.yml
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/resources/application.yml
Labels: 🌏 Deploy

#24 [Feature] 댄서 정보 관련 API 기능 구현
  src/main/java/com/danthis/backend/api/dancer/DancerController.java
  src/main/java/com/danthis/backend/api/dancer/request/DancerAddRequest.java
  src/main/java/com/danthis/backend/api/dancer/request/DancerUpdateRequest.java
  src/main/java/com/danthis/backend/application/dancer/DancerService.java
  src/main/java/com/danthis/backend/application/dancer/implement/DancerManager.java
  src/main/java/com/danthis/backend/application/dancer/implement/DancerMapper.java
  src/main/java/com/danthis/backend/application/dancer/implement/DancerReader.java
  src/main/java/com/danthis/backend/application/dancer/request/DancerAddServiceRequest.java
  src/main/java/com/danthis/backend/application/dancer/request/DancerUpdateServiceRequest.java
  src/main/java/com/danthis/backend/application/dancer/response/DancerInfoResponse.java
  src/main/java/com/danthis/backend/application/dancer/response/DancerSummaryListResponse.java
  src/main/java/com/danthis/backend/application/dancer/response/DancerSummaryResponse.java
  src/main/java/com/danthis/backend/application/dancer/response/PaginationInfo.java
  src/main/java/com/danthis/backend/application/dancergenre/implement/DancerGenreReader.java
  src/main/java/com/danthis/backend/common/exception/ErrorCode.java
  src/main/java/com/danthis/backend/domain/dancer/Dancer.java
  src/main/java/com/danthis/backend/domain/mapping/dancergenre/repository/DancerGenreRepository.java
  src/main/java/com/danthis/backend/domain/mapping/dancergenre/repository/DancerGenreRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/dancergenre/repository/DancerGenreRepositoryImpl.java
Labels: ✨ Feature

#23 [Feature] 댄서 찜 등록, 해제 기능 구현
  src/main/java/com/danthis/backend/api/userdancer/UserDancerController.java
  src/main/java/com/danthis/backend/application/dancer/DancerService.java
  src/main/java/com/danthis/backend/application/dancer/implement/DancerReader.java
  src/main/java/com/danthis/backend/application/dancer/request/DancerAddServiceRequest.java
  src/main/java/com/danthis/backend/application/userdancer/UserDancerService.java
  src/main/java/com/danthis/backend/application/userdancer/implement/UserDancerManager.java
  src/main/java/com/danthis/backend/application/userdancer/implement/UserDancerReader.java
  src/main/java/com/danthis/backend/common/exception/ErrorCode.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/repository/UserDancerRepository.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/repository/UserDancerRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/repository/UserDancerRepositoryImpl.java
Labels: ✨ Feature

#35 [ Feature] 유저가 선호하는 장르, 댄서 저장 및 조회 기능 구현
  src/main/java/com/danthis/backend/api/user/request/UserUpdateRequest.java
  src/main/java/com/danthis/backend/api/userdancer/UserDancerController.java
  src/main/java/com/danthis/backend/application/user/UserService.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/UserDancerManager.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/UserDancerReader.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/UserGenreManager.java
  src/main/java/com/danthis/backend/application/user/implement/mapping/UserGenreReader.java
  src/main/java/com/danthis/backend/application/user/request/UserUpdateServiceRequest.java
  src/main/java/com/danthis/backend/application/userdancer/UserDancerService.java
  src/main/java/com/danthis/backend/application/userdancer/implement/UserDancerManager.java
  src/main/java/com/danthis/backend/application/userdancer/implement/UserDancerReader.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/repository/UserDancerRepository.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/repository/UserDancerRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/userdancer/repository/UserDancerRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/mapping/usergenre/repository/UserGenreRepository.java
  src/main/java/com/danthis/backend/domain/mapping/usergenre/repository/UserGenreRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/mapping/usergenre/repository/UserGenreRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/user/User.java
Labels: ✨ Feature, 🔨 Refactor

#36 [Feature] 회원가입 유무를 판별하는 기능 구현
  src/main/java/com/danthis/backend/api/user/UserController.java
  src/main/java/com/danthis/backend/application/user/UserService.java
  src/main/java/com/danthis/backend/application/user/implement/UserReader.java
  src/main/java/com/danthis/backend/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/user/repository/UserRepositoryImpl.java
Labels: ✨ Feature

#33 [Feature] 댄스 수업 조회 기능 구현
  src/main/java/com/danthis/backend/api/danceclass/DanceClassController.java
  src/main/java/com/danthis/backend/api/danceclass/request/DanceClassCreateRequest.java
  src/main/java/com/danthis/backend/api/review/ReviewController.java
  src/main/java/com/danthis/backend/api/review/request/ReviewCreateRequest.java
  src/main/java/com/danthis/backend/application/danceclass/DanceClassService.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassMapper.java
  src/main/java/com/danthis/backend/application/danceclass/implement/DanceClassReader.java
  src/main/java/com/danthis/backend/application/danceclass/response/DanceClassListServiceResponse.java
  src/main/java/com/danthis/backend/application/danceclass/response/DanceClassReadServiceResponse.java
  src/main/java/com/danthis/backend/application/review/ReviewService.java
  src/main/java/com/danthis/backend/application/review/implement/ReviewManager.java
  src/main/java/com/danthis/backend/application/review/implement/ReviewMapper.java
  src/main/java/com/danthis/backend/application/review/implement/ReviewReader.java
  src/main/java/com/danthis/backend/application/review/request/ReviewCreateServiceRequest.java
  src/main/java/com/danthis/backend/application/review/response/ReviewReadServiceResponse.java
  src/main/java/com/danthis/backend/common/exception/ErrorCode.java
  src/main/java/com/danthis/backend/domain/classreview/repository/ClassReviewRepository.java
  src/main/java/com/danthis/backend/domain/classreview/repository/ClassReviewRepositoryCustom.java
  src/main/java/com/danthis/backend/domain/classreview/repository/ClassReviewRepositoryImpl.java
  src/main/java/com/danthis/backend/domain/danceclass/repository/DanceClassRepository.java
  src/main/java/com/danthis/backend/domain/dancer/Dancer.java
Labels: ✨ Feature
